# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["api", "application", "domain", "infrastructure", "shared"]


[workspace.dependencies]
diesel = { version = "2.0.0", features = ["postgres"] }
rocket = { version = "0.5.0-rc.2", features = ["json"] }
serde = { version = "1.0.147" }
serde_json = "1.0.88"
