# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["api", "application", "domain", "infrastructure", "shared"]


[workspace.dependencies]
diesel = { version = "2.0.0", features = [
    "r2d2",
    "postgres",
] } #Keep diesel version up to date with sync_db_pools
rocket = { git = "https://github.com/SergioBenitez/Rocket", branch = "master", features = [
    "json",
] }
rocket_sync_db_pools = { git = "https://github.com/SergioBenitez/Rocket", branch = "master", features = [
    "diesel_postgres_pool",
] }

serde = { version = "1.0.147" }
serde_json = "1.0.88"
