version: '3.1'

services:
  db:
    image: postgres:14-alpine3.16
    restart: always
    environment:
      POSTGRES_USER: cos
      POSTGRES_PASSWORD: password
  api:
    build: ./Dockerfile
    restart: always
    ports:
      - 8000:8080