version: '3.1'

services:
  db:
    image: postgres:14-alpine3.16
    restart: always
    volumes:
      - cos_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cos
      POSTGRES_PASSWORD: password
  api:
    build: ./Dockerfile
    restart: always
    ports:
      - 8000:8000

volumes:
  cos_data:
    external: true