## defaults for _all_ profiles
[default]
address = "0.0.0.0"

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
port = 8000
limits = { json = "10MiB" }

## set only when compiled in release mode, i.e, `cargo build --release`
[release]
port = 3002
