# shared/Cargo.toml

[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }

sqlx = { workspace = true, default-features = false, features = [] }
serde = { workspace = true, features = ["derive"] }
axum = { workspace = true }
